---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmp-spring-petclinic-run
  labels:
    app.kubernetes.io/name: spring-petclinic-run
    app.kubernetes.io/instance: jmp
    app.kubernetes.io/version: "1.19.7"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-petclinic-run
      app.kubernetes.io/instance: jmp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring-petclinic-run
        app.kubernetes.io/instance: jmp
    spec:
      serviceAccountName: jmp-spring-petclinic-run
      containers:
        - name: spring-petclinic-run
          image: spring-petclinic-run
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
          - name: app-config
            mountPath: /application.yml
            subPath: application.yml
            readOnly: true
      volumes:
      - name: app-config
        configMap:
          name: jmp-spring-petclinic-run
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jmp-spring-petclinic-run
  labels:
    app.kubernetes.io/name: spring-petclinic-run
    app.kubernetes.io/instance: jmp
    app.kubernetes.io/version: "1.19.7"
---
apiVersion: v1
kind: Service
metadata:
  name: jmp-spring-petclinic-run
  labels:
    app.kubernetes.io/name: spring-petclinic-run
    app.kubernetes.io/instance: jmp
    app.kubernetes.io/version: "1.19.7"
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: spring-petclinic-run
    app.kubernetes.io/instance: jmp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jmp-spring-petclinic-run
  labels:
    app.kubernetes.io/name: spring-petclinic-run
    app.kubernetes.io/instance: jmp
    app.kubernetes.io/version: "1.19.7"
data:
  application.yml:  |
    server:
      port: 8083

